name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
  
  secon_job:
    if: ${{github.ref == 'ref/heads/main'}}
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"