name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: working dir
        run: la -la

      - name: working dir
        uses: actions/checkout@v4

      - name: working dir after action
        run: ls -la
  
  secon_job:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"