name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: working dir
        run: echo $GITHUB_OUTPUT
  
  secon_job:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"